### ISSUE TITLE
Mixed-Content Errors when Embedding Cards in HTTPS

### ISSUE THREAD

**Issue by hariharshankar** [oduwsdl/MementoEmbed#124]
The Javascript file that the embedded cards use is always using the HTTP protocol even when served from an HTTPS domain. 
`<script async src="http://mementoembed.myresearch.institute/static/js/mementoembed-v20180806.js" charset="utf-8"></script>`

The browsers are blocking this script because of mixed-content, and hence the card is not rendered correctly.

**Comment by ibnesayeed** [comment]
This issue was realized earlier in #95 and I think the current fix is to run the MementoEmbed server on HTTPS if the cards are to be used in an HTTPS page.

I don't think it always returns an HTTP URI as it utilizes the variable `urlroot`, but if your tests are shoing that then perhaps there is a bug somewhere.

https://github.com/oduwsdl/MementoEmbed/blob/0e8f812dff1bab8edf0d5f9a528364dbca2e76a5/mementoembed/services/product.py#L49

https://github.com/oduwsdl/MementoEmbed/blob/3f412b5f93aede56e78618c7164567a871641c17/mementoembed/services/oembed.py#L70-L71

**Comment by hariharshankar** [comment]
The MementoEmbed server is on HTTPS and we are trying to embed the card into another HTTPS page. 

We do not see this error at the endpoint: `/ui/product/socialcard/`. However, we do see it at the endpoint `/services/product/socialcard/`.

**Comment by ibnesayeed** [comment]
That is certainly a bug then. @shawnmjones should be able to investigate it.

**Comment by shawnmjones** [comment]
Thanks @ibnesayeed for mentioning #95. @hariharshankar and I spoke about this offline and I asked him to put this ticket in so I could track it.
