### ISSUE TITLE
Bad Image URL in the Social Cards when data-image Attribute is None

### ISSUE THREAD

**Issue by hariharshankar** [oduwsdl/MementoEmbed#128]
For some Mementos, the `/services/product/socialcard/` API returns `data-image="None"`. In these scenarios, the `generate_cards()` JS method creates the social card image in `#me-image` with `src="None"`. 

Either the check in the `generate_cards()` could account for `None` or the `<blockquote>` tag could omit properties that are `None`.

**Comment by shawnmjones** [comment]
Thanks for the heads up. I'll investigate.

**Comment by ibnesayeed** [comment]
https://github.com/oduwsdl/MementoEmbed/blob/a4a9df9b68f3353a1a28759161ba14c48fbbf04e/mementoembed/services/memento.py#L106

On a quick note I think replacing above line with the following should do the trick:

```py
output['best-image-uri'] = best_image_uri or ''
```

**Comment by shawnmjones** [comment]
Thanks @ibnesayeed, but the JavaScript should be less brittle. Only fixing the problem in `/services/memento.py` ignores the machine endpoints in `/services/product.py`.

**Comment by ibnesayeed** [comment]
Well, it has to do with how Python converts `None` to string. While `None` is a falsy object in boolean context, when converted to string it does not return a falsy string (i.e. an empty sting).

```py
>>> str(None)
'None'
```

This means we need to be careful where we not want that to happen. One way to fix this issue for various different places where it might be used is to change the default value of `max_score_image` from `None` to an empty string at the following line.

https://github.com/oduwsdl/MementoEmbed/blob/7d628bba233bb249f221af984c84a9ac71e37bb9/mementoembed/imageselection.py#L113

**Comment by shawnmjones** [comment]
The problem is actually larger that that. This is part of it, but there is a larger issue with the image selection code. I'll give details soon.

**Comment by ibnesayeed** [comment]
A similar issue often surfaces in JS as well where falsy `null` or `undefined` will be converted to strings as a word, not an empty string. I usually use a similar logical operator trick to canonicalize such variables in string context [as it can be seen in the Reconstructive repo](https://github.com/oduwsdl/Reconstructive/blob/e048c5f62f3c16c36808ff22a4b04c00c9ab7004/reconstructive.js#L359-L366).

```js
rels.first && rels.first.href || ''
```

The above JS line can be interpreted as:

```js
(rels.first && rels.first.href) || ''
```

The way logical operators are executed is if there is an AND between two statements, the value of the first one will be returned if it is falsy, otherwise the value of the second will be returned instead. And if there is an OR then the first one will be returned if it is truthy, otherwise the value of the second one will be returned instead.

So, in the above example it means check the value of `rels.first.href` if and only if `rels.first` is not `nill` (to avoid an exception like `cannot read property 'href' of nill object`) and return the value of `rels.first.href` if it is not falsy. Otherwise the statement in parenthesis returns falsy (due to the first one or the second) then return the value after the OR operator, which is an empty string.
