### ISSUE TITLE
Improvements should be made to the thumbnails generated for NLA mementos  

### ISSUE THREAD

**Issue by himarshaj** [oduwsdl/MementoEmbed#173]
Test URI-Ms:

1. https://webarchive.nla.gov.au/awa/20160210010019/http://pandora.nla.gov.au/pan/156727/20160210-1200/www.barefaced.com.au/index.html

2. https://webarchive.nla.gov.au/awa/20160229080832/http://www.barefaced.com.au/

Thumbnails generated through MementoEmbed for the above NLA URI-Ms:

Thumbnail 1
 ![image](https://user-images.githubusercontent.com/53842088/109579489-fa83ff80-7ac6-11eb-95a0-d8bacaa67737.png)

Thumbnail 2
 ![image](https://user-images.githubusercontent.com/53842088/109580630-e3dea800-7ac8-11eb-8807-9baa7b4d99bc.png)

It appears that the screenshot to be used as the thumbnail is captured from the URI-M at Trove too soon before the page completely loads.

**Comment by shawnmjones** [comment]
MementoEmbed's Python code calls a Puppeteer script as an external process to take the screenshot. To solve the problem you've documented here, I first thought that we could raise the THUMBNAIL_TIMEOUT value in this config file used during development:

https://github.com/oduwsdl/MementoEmbed/blob/71de6551676f4835a244e7ac5ec8259851bf0081/config/default.py#L13

or this config file used in the Docker container:

https://github.com/oduwsdl/MementoEmbed/blob/71de6551676f4835a244e7ac5ec8259851bf0081/sample_appconfig.cfg#L77-L79

but the value is set to 300 seconds, which is 5 minutes. This is how long the Python code will wait for Puppeter before giving up.

Our Trove examples produce (poor) thumbnails much faster than 5 minutes, so that timeout is clearly not in play. Instead, I wonder if the screenshot code itself needs to be modified.

https://github.com/oduwsdl/MementoEmbed/blob/71de6551676f4835a244e7ac5ec8259851bf0081/mementoembed/static/js/create_screenshot.js#L27

I don't remember what units `page.waitFor` will take. According to the [Puppeteer source code for the Page class](https://github.com/puppeteer/puppeteer/blob/be7c22933c1dcf5eee797d61463171bd0ef44582/src/common/Page.ts), the `waitFor` method can accept `a selector, predictor or timeout to wait for`.  Maybe that would be helpful?

**Comment by himarshaj** [comment]
Making adjustments to the "await page.waitFor(2000)" did not make a difference.

However, using [page.waitForNavigation](https://pptr.dev/#?product=Puppeteer&version=v8.0.0&show=api-pagewaitfornavigationoptions) to control the time before the screenshot is taken improved the state of thumbnails, but it was not good enough.

`await page.waitForNavigation({
 waitUntil: 'networkidle0',
});`

When using "networkidle0",  it waits for the network to be idle for 500ms. While there is no option to control the wait time/timeout there, we could [emulate the puppeteer code](https://github.com/puppeteer/puppeteer/issues/1353#issuecomment-356561654) to adjust the timeout. Tested with a timeout value of 2000ms instead of 500ms. 

Test URI-M: https://webarchive.nla.gov.au/awa/20190305233656/http://www.barefaced.com.au/

![image](https://user-images.githubusercontent.com/53842088/110229953-1b8b8c80-7edb-11eb-8022-1ff4ff2243ef.png)

The thumbnail generated looks much better. We can try making adjustments to this timeout value to set the most suitable value considering the trade-off between the quality of the thumbnail and the time to generate the thumbnail.
