### ISSUE TITLE
handle all exceptions thrown for images and favicons

### ISSUE THREAD

**Issue by phonedude** [oduwsdl/MementoEmbed#86]
for http://archive.is/Q8pGf I just now recvd:

  The URI-M http://archive.is/Q8pGf is not valid

and with: http://archive.is/MIq1y

I just got: 

  MementoEmbed could not reach the server to download http://archive.is/MIq1y

you might need to contact webmaster@archive.is and get this service whitelisted.

**Comment by shawnmjones** [comment]
The user-agent string is whitelisted (or at least was last week).

Local testing reveals behavior indicating that the user-agent string might have been overwritten.

Thanks for this.

**Comment by shawnmjones** [comment]
Based on what I have observed, Archive.is returns a "bad ZIP file" if it does not like the user-agent string or the source IP address. My initial thought was that the request headers were being overwritten. It turns out I was incorrect.

Testing outside of the application reveals that updating the request headers does not remove the user agent string.

Here is an iPython session using the same libraries we do for HTTP requests and caching:
```
In [1]: import requests

In [2]: import requests_cache

In [3]: requests_cache.install_cache('/tmp/testcache')

In [4]: httpcache = requests.Session()

In [5]: httpcache.headers.update({ 'User-Agent': 'ShawnTest/0.0' })

In [6]: httpcache.get("http://www.shawnmjones.org/publications/")
Out[6]: <Response [200]>

In [7]: httpcache.get("http://www.shawnmjones.org/presentations/", headers={ 'X-Test-Header': 'hello' })
Out[7]: <Response [200]>
```

Responses in the server log of www.shawnmjones.org:
```
76.113.71.139 - - [06/Jul/2018:14:56:58 -0400] "GET /publications/ HTTP/1.1" 200 4400 "-" "ShawnTest/0.0"
76.113.71.139 - - [06/Jul/2018:14:57:07 -0400] "GET /presentations/ HTTP/1.1" 200 3797 "-" "ShawnTest/0.0"
```

Even though I updated the headers in the `In [7]`, the user-agent that was established at `In [5]` was still set and recorded by the server.

**Comment by shawnmjones** [comment]
Instead, I should have looked in the logs of the running application at mementoembed.ws-dl.cs.odu.edu. There were two archive.is URI-Ms submitted: `http://archive.is/Q8pGf` and `http://archive.is/MIq1y`.

For `http://archive.is/Q8pGf`:
```
2018-07-05 16:08:47,606 [WARNING] mementoembed: An unsupported/invalid URI-M http://archive.is/Q8pGf was submitted, details: Invalid URL '//abs.twimg.com/favic
ons/favicon.ico': No schema supplied. Perhaps you meant http:////abs.twimg.com/favicons/favicon.ico?
```

This URI is rejected by the requests library because it has no schema. The generic error message received in the paragraph opening this issue indicates that there is a problem with the URI-M submitted, which is not true. Both the log message and the user-facing error message need to be updated to be more clear.

For `http://archive.is/MIq1y`:
```
2018-07-05 16:10:42,319 [WARNING] mementoembed: The server for URI-M http://archive.is/MIq1y could not be reached, details: HTTPConnectionPool(host='128.82.7.3.us.cby5.190433754.pixel.archive.is', port=80): Max retries exceeded with url: /pixel.gif (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3eafbb0550>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

The system failed because it was trying to download the URI `/pixel.gif`, which it failed to do because it is not an absolute URI. Again, the user-facing error message and the log message need to be more clear.

The `image_selection_failure` branch that I am working on may have a fix for this issue already in place. As one of its many fixes, that branch skips over images that generate exceptions on download.

**Comment by shawnmjones** [comment]
For `http://archive.is/MIq1y` the image should have been handled by the urljoin on line 54 here:

https://github.com/oduwsdl/MementoEmbed/blob/ea3c255b5f1987ee5764c25d004f0e09628b3d67/mementoembed/imageselection.py#L45-L59

Again, the log message is not as informative as expected. The actual URI of the image was likely something like "http://128.82.7.3.us.cby5.190433754.pixel.archive.is/pixel.gif".

When I visited `http://archive.is/MIq1y` today, the HTML contains the image URI of: "http://76.113.71.139.us.cby5.190433754.pixel.archive.is/pixel.gif", which fails to load in Google Chrome (and is silently ignored) and I cannot access it via curl:

```
# curl -I "http://76.113.71.139.us.cby5.190433754.pixel.archive.is/pixel.gif"
curl: (6) Could not resolve host: 76.113.71.139.us.cby5.190433754.pixel.archive.is
```

The first part of the URI appears to be the IP address of the client. This may be some kind of identification mechanism for page visitors. In any case, the`image_selection_failure` branch should handle this because it wraps all image requests in try/except clauses and ignores images for which there were download issues.

**Comment by shawnmjones** [comment]
For `http://archive.is/Q8pGf` the favicon URI `//abs.twimg.com/favicons/favicon.ico`has no schema and thus the `requests` library does not know what to do with it.

On the one hand, the `image_selection_failure` branch should handle this because it wraps all favicon requests in try/except clauses and moves on if they fail to download.

On the other hand, can we "fix" this favicon URI to have the correct schema? Do we assume that it is https? Should we do that for other URIs we encounter? That sounds like it needs a separate issue.

**Comment by shawnmjones** [comment]
For `http://archive.is/Q8pGf`, the following social card is now generated:

![2018-07-06_17-34-23](https://user-images.githubusercontent.com/4702031/42404018-e71824ce-8142-11e8-9d1c-7dd4c15ba452.png)

**Comment by shawnmjones** [comment]
For `http://archive.is/MIq1y`, the following social card is now generated in **testing**:

![2018-07-06_17-36-16](https://user-images.githubusercontent.com/4702031/42404068-364e2c14-8143-11e8-9f94-79251414c7a7.png)

**Comment by shawnmjones** [comment]
And that `Current version unavailable` is accurate:

```
# curl -IL "http://www.egr.vcu.edu/news-events/events/cs-seminar-michael-l-nelson-phd.html"
HTTP/1.1 301 Moved Permanently
Date: Fri, 06 Jul 2018 23:38:44 GMT
Location: https://egr.vcu.edu/news-events/events/cs-seminar-michael-l-nelson-phd.html
Content-Type: text/html; charset=iso-8859-1
Set-Cookie: TS01d5e815=01eb2dad4b4524f4e3bd672d9907f21b6d95db8224bbab9bc6c1f032904fcf92e07cd16e748279625320777a2e045055a564f955e2; Path=/; Domain=.vcu.edu
Transfer-Encoding: chunked

HTTP/1.1 404 Not Found
Date: Fri, 06 Jul 2018 23:38:45 GMT
Last-Modified: Mon, 02 Jul 2018 22:00:29 GMT
ETag: "12ffed1a5-3b8a-5700b535b5940;5700a0dcbd7c0"
Accept-Ranges: bytes
Content-Length: 15242
Content-Type: text/html
Set-Cookie: TS019dfe1f=01eb2dad4b905f905fea52c0a910f13ec248ac3685161213c6b45d68b1805448c3f9ba853dfc823cf7c2dddb66da2e07da786b53af; Path=/; Domain=.egr.vcu.edu
```
