### ISSUE TITLE
Bad URL: https://cs.odu.edu

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/MementoEmbed#89]
It's a URI-R, yes, but the system shows a "spinner" that does not stop after waiting > 1 minute.

**Comment by shawnmjones** [comment]
So, this is a result of a decision I made early on to be patient with archives because it takes a while for them to look up mementos.

Using that URI, I get the following from curl.

```
# time curl -I "https://cs.odu.edu"
curl: (7) Failed to connect to cs.odu.edu port 443: Operation timed out

real	2m30.954s
user	0m0.007s
sys	0m0.007s
```

It takes 2 minutes and 30 seconds for curl to decide to give up. I need to determine when I should give up on a given URI-M. Seeing as 30 - 45 seconds seems like a long enough time period for wait for card generation, maybe I should give a URI-M a 20 - 25 second timeout?

**Comment by shawnmjones** [comment]
And here are the log messages you generated when trying this.

```
2018-07-05 16:21:36,907 [WARNING] mementoembed: The server for URI-M https://cs.odu.edu could not be reached, details: HTTPSConnectionPool(host='cs.odu.edu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3eaf38eb00>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

and

```
2018-07-05 16:21:53,291 [WARNING] mementoembed: The server for URI-M https://cs.odu.edu could not be reached, details: HTTPSConnectionPool(host='cs.odu.edu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3eafc1bb70>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

**Comment by shawnmjones** [comment]
So, I looked into setting a timeout via the `requests` library, which easily be done as per http://docs.python-requests.org/en/master/user/quickstart/#timeouts

Unfortunately, it can't be set globally for the `requests` session object, which has created some controversy in the community:
* https://github.com/requests/requests/issues/1563
* https://github.com/requests/requests/issues/3341

The first discussion is from 2013, but the last discussion was locked and limited to collaborators as of 4 days ago, meaning that something may happen on this... someday.

Inheriting from the `requests` session object can provide a solution, but it seems silly to have to do this just to set a timeout value for the whole session.

**Comment by machawk1** [comment]
@shawnmjones Maybe you can use a thread to wrap the request, set a timeout on the thread, and throw an exception if the timeout expires before the request is returned. We were doing something like that with ipwb (in waiting for IPFS to respond) but the exception that is invoked (SIGALARM) does not work on Windows, which was needed for that project (but maybe not critical for MementoEmbed).

**Comment by shawnmjones** [comment]
Thanks for the suggestion @machawk1. The frustrating thing is that the `requests` library does handle this natively, essentially what you are describing, on a per-request basis. I was just hoping that I could set the timeout in one place instead of having to pass the timeout to every function that needs it.

I'm already passing a session object around to ensure that all HTTP traffic **per submission** exists within the same session. I was already thinking of making it smart enough to set the referrer for image mementos and favicons. And now I need to set timeouts. Extending (or subclassing, or wrapping) the session object seems to be something that the code is already suited for. You've convinced me of it.
